application:
  id: jpa-multidb-tutorials
  version: 1.0

spring:
  profiles:
    active: local
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace


server:
  port: 8080